# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config-service.proto',
  package='config',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x63onfig-service.proto\x12\x06\x63onfig\"M\n\x11SetDesiredRequest\x12\x11\n\tdeviceEUI\x18\x01 \x01(\t\x12\x11\n\tfieldName\x18\x02 \x01(\t\x12\x12\n\nfieldValue\x18\x03 \x01(\t\"b\n\x17\x43heckConsistencyRequest\x12\x11\n\tdeviceEUI\x18\x01 \x01(\t\x12\x0c\n\x04slot\x18\x02 \x01(\x05\x12\x12\n\nfieldIndex\x18\x03 \x01(\x05\x12\x12\n\nnumRetries\x18\x04 \x01(\x05\"R\n\x15UpdateReportedRequest\x12\x11\n\tdeviceEUI\x18\x01 \x01(\t\x12\x12\n\nfieldIndex\x18\x02 \x01(\x05\x12\x12\n\nfieldValue\x18\x03 \x01(\t\"\x1e\n\tDeviceEUI\x12\x11\n\tdeviceEUI\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05reply\x18\x01 \x01(\t\"3\n\x0c\x43onfigFields\x12#\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x13.config.ConfigField\"Q\n\x0b\x43onfigField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65sired\x18\x02 \x01(\t\x12\x10\n\x08reported\x18\x03 \x01(\t\x12\x11\n\tfieldType\x18\x04 \x01(\t2\xcf\x02\n\rConfigService\x12;\n\nSetDesired\x12\x19.config.SetDesiredRequest\x1a\x10.config.Response\"\x00\x12G\n\x10\x43heckConsistency\x12\x1f.config.CheckConsistencyRequest\x1a\x10.config.Response\"\x00\x12\x43\n\x0eUpdateReported\x12\x1d.config.UpdateReportedRequest\x1a\x10.config.Response\"\x00\x12\x39\n\x0cGetAllConfig\x12\x11.config.DeviceEUI\x1a\x14.config.ConfigFields\"\x00\x12\x38\n\x0f\x43reateNewConfig\x12\x11.config.DeviceEUI\x1a\x10.config.Response\"\x00\x62\x06proto3')
)




_SETDESIREDREQUEST = _descriptor.Descriptor(
  name='SetDesiredRequest',
  full_name='config.SetDesiredRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceEUI', full_name='config.SetDesiredRequest.deviceEUI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldName', full_name='config.SetDesiredRequest.fieldName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldValue', full_name='config.SetDesiredRequest.fieldValue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=109,
)


_CHECKCONSISTENCYREQUEST = _descriptor.Descriptor(
  name='CheckConsistencyRequest',
  full_name='config.CheckConsistencyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceEUI', full_name='config.CheckConsistencyRequest.deviceEUI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot', full_name='config.CheckConsistencyRequest.slot', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldIndex', full_name='config.CheckConsistencyRequest.fieldIndex', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numRetries', full_name='config.CheckConsistencyRequest.numRetries', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=209,
)


_UPDATEREPORTEDREQUEST = _descriptor.Descriptor(
  name='UpdateReportedRequest',
  full_name='config.UpdateReportedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceEUI', full_name='config.UpdateReportedRequest.deviceEUI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldIndex', full_name='config.UpdateReportedRequest.fieldIndex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldValue', full_name='config.UpdateReportedRequest.fieldValue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=293,
)


_DEVICEEUI = _descriptor.Descriptor(
  name='DeviceEUI',
  full_name='config.DeviceEUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceEUI', full_name='config.DeviceEUI.deviceEUI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=325,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='config.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='config.Response.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=352,
)


_CONFIGFIELDS = _descriptor.Descriptor(
  name='ConfigFields',
  full_name='config.ConfigFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='config.ConfigFields.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=405,
)


_CONFIGFIELD = _descriptor.Descriptor(
  name='ConfigField',
  full_name='config.ConfigField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='config.ConfigField.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desired', full_name='config.ConfigField.desired', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reported', full_name='config.ConfigField.reported', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldType', full_name='config.ConfigField.fieldType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=488,
)

_CONFIGFIELDS.fields_by_name['fields'].message_type = _CONFIGFIELD
DESCRIPTOR.message_types_by_name['SetDesiredRequest'] = _SETDESIREDREQUEST
DESCRIPTOR.message_types_by_name['CheckConsistencyRequest'] = _CHECKCONSISTENCYREQUEST
DESCRIPTOR.message_types_by_name['UpdateReportedRequest'] = _UPDATEREPORTEDREQUEST
DESCRIPTOR.message_types_by_name['DeviceEUI'] = _DEVICEEUI
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ConfigFields'] = _CONFIGFIELDS
DESCRIPTOR.message_types_by_name['ConfigField'] = _CONFIGFIELD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetDesiredRequest = _reflection.GeneratedProtocolMessageType('SetDesiredRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETDESIREDREQUEST,
  '__module__' : 'config_service_pb2'
  # @@protoc_insertion_point(class_scope:config.SetDesiredRequest)
  })
_sym_db.RegisterMessage(SetDesiredRequest)

CheckConsistencyRequest = _reflection.GeneratedProtocolMessageType('CheckConsistencyRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKCONSISTENCYREQUEST,
  '__module__' : 'config_service_pb2'
  # @@protoc_insertion_point(class_scope:config.CheckConsistencyRequest)
  })
_sym_db.RegisterMessage(CheckConsistencyRequest)

UpdateReportedRequest = _reflection.GeneratedProtocolMessageType('UpdateReportedRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREPORTEDREQUEST,
  '__module__' : 'config_service_pb2'
  # @@protoc_insertion_point(class_scope:config.UpdateReportedRequest)
  })
_sym_db.RegisterMessage(UpdateReportedRequest)

DeviceEUI = _reflection.GeneratedProtocolMessageType('DeviceEUI', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEEUI,
  '__module__' : 'config_service_pb2'
  # @@protoc_insertion_point(class_scope:config.DeviceEUI)
  })
_sym_db.RegisterMessage(DeviceEUI)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'config_service_pb2'
  # @@protoc_insertion_point(class_scope:config.Response)
  })
_sym_db.RegisterMessage(Response)

ConfigFields = _reflection.GeneratedProtocolMessageType('ConfigFields', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGFIELDS,
  '__module__' : 'config_service_pb2'
  # @@protoc_insertion_point(class_scope:config.ConfigFields)
  })
_sym_db.RegisterMessage(ConfigFields)

ConfigField = _reflection.GeneratedProtocolMessageType('ConfigField', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGFIELD,
  '__module__' : 'config_service_pb2'
  # @@protoc_insertion_point(class_scope:config.ConfigField)
  })
_sym_db.RegisterMessage(ConfigField)



_CONFIGSERVICE = _descriptor.ServiceDescriptor(
  name='ConfigService',
  full_name='config.ConfigService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=491,
  serialized_end=826,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetDesired',
    full_name='config.ConfigService.SetDesired',
    index=0,
    containing_service=None,
    input_type=_SETDESIREDREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckConsistency',
    full_name='config.ConfigService.CheckConsistency',
    index=1,
    containing_service=None,
    input_type=_CHECKCONSISTENCYREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateReported',
    full_name='config.ConfigService.UpdateReported',
    index=2,
    containing_service=None,
    input_type=_UPDATEREPORTEDREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllConfig',
    full_name='config.ConfigService.GetAllConfig',
    index=3,
    containing_service=None,
    input_type=_DEVICEEUI,
    output_type=_CONFIGFIELDS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateNewConfig',
    full_name='config.ConfigService.CreateNewConfig',
    index=4,
    containing_service=None,
    input_type=_DEVICEEUI,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGSERVICE)

DESCRIPTOR.services_by_name['ConfigService'] = _CONFIGSERVICE

# @@protoc_insertion_point(module_scope)
